INSERT INTO STUDENT (ID, NAME, EMAIL) VALUES(1, 'jj','111@yahoo.com');
INSERT INTO STUDENT (ID, NAME, EMAIL) VALUES(2, 'vv','222@yahoo.com');
INSERT INTO EMPLOYEE (ID, NAME, EMAIL) VALUES(2, 'vv','222@yahoo.com');
INSERT INTO EMPLOYEE (ID, NAME, EMAIL) VALUES(1, 'jj','111@yahoo.com');
