INSERT INTO STUDENT (ID, NAME, EMAIL) VALUES(1, 'aa','aa@yahoo.com');
INSERT INTO STUDENT (ID, NAME, EMAIL) VALUES(2, 'bb','bb@yahoo.com');
INSERT INTO STUDENT (ID, NAME, EMAIL) VALUES(3, 'cc','cc@yahoo.com');
INSERT INTO STUDENT (ID, NAME, EMAIL) VALUES(4, 'dd','dd@yahoo.com');
INSERT INTO STUDENT (ID, NAME, EMAIL) VALUES(5, 'ee','ee@yahoo.com');
INSERT INTO STUDENT (ID, NAME, EMAIL) VALUES(6, 'ff','ff@yahoo.com');

INSERT INTO EMPLOYEE(ID, NAME, EMAIL) VALUES(1, 'aa','aa@yahoo.com');
INSERT INTO EMPLOYEE(ID, NAME, EMAIL) VALUES(2, 'bb','bb@yahoo.com');
INSERT INTO EMPLOYEE(ID, NAME, EMAIL) VALUES(3, 'cc','cc@yahoo.com');
INSERT INTO EMPLOYEE(ID, NAME, EMAIL) VALUES(4, 'dd','dd@yahoo.com');
INSERT INTO EMPLOYEE(ID, NAME, EMAIL) VALUES(5, 'ee','ee@yahoo.com');
INSERT INTO EMPLOYEE(ID, NAME, EMAIL) VALUES(6, 'ff','ff@yahoo.com');

